/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Store__factory } from "./Store__factory";
export { StoreBase__factory } from "./StoreBase__factory";
