"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StoreBase__factory = exports.Store__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Store__factory_1 = require("./Store__factory");
Object.defineProperty(exports, "Store__factory", { enumerable: true, get: function () { return Store__factory_1.Store__factory; } });
var StoreBase__factory_1 = require("./StoreBase__factory");
Object.defineProperty(exports, "StoreBase__factory", { enumerable: true, get: function () { return StoreBase__factory_1.StoreBase__factory; } });
