name: Test Project
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Download repository
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Compile contract
              run: npx hardhat compile
            - name: Deploy contract
              run: npx hardhat run scripts/deployStore.ts --network localhost
            - name: Run tests
              run: npx hardhat test --network localhost