name: Dev CI
on:
    workflow_dispatch:
    push:
        branches:
            - main  
    pull_request:
        types:
            - opened
            - edited
jobs:
    BuildContract:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
                
            - name: Install dependencies
              run: npm ci

            - name: Compile contract
              run: npx hardhat compile
              
            - name: Upload deploy artifacts
              uses: actions/upload-artifact@v4
              with:
                path: typechain-types

    Test:
      needs: BuildContract
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v4

        - name: Cache dependencies
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

        - name: Install dependencies
          run: npm ci

        - name: Download deploy contracts
          uses: actions/download-artifact@v4
          with:
            path: typechain-types

        - name: Start local HardHat node in background
          run: nohup npx hardhat node > node.log 2>&1 &

        - name: Deploy contract
          run: npx hardhat run scripts/deployStore.ts --network localhost

        - name: Run tests
          run: npx hardhat test --parallel --network localhost

        - name: Run tests and generate code coverage
          run: npx hardhat coverage

        - name: Verify full code coverage
          run: npx istanbul check-coverage ./coverage.json --statements 100 --branches 100 --functions 100 --lines 100